
export const Resources = [
    { title: "Need help? Here are some mental health hotlines", 
    content: "National Institute for Mental Health\n0917 989 8727 (Globe & TM)\n0908 639 2672 (Smart, Sun, TNT)\n\nIn Touch Philippines\n(02) 893 7603 (Landline)\n0917 800 1123 (Globe)\n0922 893 8944 (Sun)\n\nPhilippine Red Cross\n(02) 8044673 (Landline)\nHOPELINE 2919 (Globe & TM)\n0917 558 4673\n\nManila Lifeline Centre \n(02) 8969191 (Landline)\n0917 854 9191",
    link: "https://www.mhfirstresponse.org/crisis--treatment-centers.html" },

    { title: "3-Minute Mindfulness (Breathing Exercises)", 
    content: "Practicing mindful breathing can help you access the part of your nervous system that allows you to reduce stress and think more clearly, which will keep you safer and eliminate the overwhelmed feeling that often accompanies anxiety and panic.\n\nWith one breath, what many call a “relaxation breath,” you can trick your brain back into relaxation mode.\n\nHere’s a simple three-minute exercise you can use no matter where you are.\n\n1. Sit or stand up nice and tall. Let your eyes relax. Relax your jaw. Let your shoulders relax down your back and start to focus your attention on your breath.\n2. Breathe all the way in through your nose, filling your belly with your breath. Then, breathe all the way out through your nose. It’s that simple.\n3. Start to breathe into a count of three. Inhale for one, two, three. Then, exhale into a count of six: six, five, four, three, two and one.\n4. Repeat. Inhale: one, two, three. Exhale: six, five, four, three, two and one.\n5. Continue just like this for three minutes, or as long as you'd like. You can set a timer on your phone at the beginning of your practice.\n\nShould your mind wander, simply notice, without judgment. Observe your thoughts. And let it go. Return your breath to your attention as many times as it takes, training your mind in the same way we train our bodies.", 
    link: "https://blog.ochsner.org/articles/3-minute-mindful-breathing-exercise-for-anxiety-relief" },

    { title: "Dealing with Anxiety", 
    content: "Here are different ways on how to calm yourself down in case of an anxiety or panic attack:\n\n1. Visualize\nSit in a quiet and comfortable place. Think of your ideal place to relax. While it can be any place in the world, real or imaginary, it should be an image that you find very calming, happy, peaceful, and safe. Make sure it’s easy enough to think about so you can return to it in your mind when you feel anxious in the future. Think of all the small details you’d find if you were there. Think about how the place would smell, feel, and sound. Envision yourself in that place, enjoying it comfortably. Once you have a good picture of your “happy place,” close your eyes and take slow and regular breaths through your nose and out of your mouth. Be aware of your breathing and continue focusing on the place you’ve imagined in your mind until you feel your anxiety lifting. Visit this place in your mind whenever you feel anxious.\n\n2. Relax your muscles\nMuscle stress can make your anxiety more difficult to manage in the moment you’re experiencing it. By relieving the stress in your muscles, you can usually reduce your anxiety levels. To quickly relieve your muscle tension during moments of anxiety:\n\n* Sit in a quiet and comfortable place. Close your eyes and focus on your breathing. Breathe slowly into your nose and out of your mouth.\n* Use your hand to make a tight fist. Squeeze your fist tightly.\n* Hold your squeezed fist for a few seconds. Notice all the tension you feel in your hand.\n* Slowly open your fingers and be aware of how you feel. You may notice a feeling of tension leaving your hand. Eventually, your hand will feel lighter and more relaxed.\n* Continue tensing and then releasing various muscle groups in your body, from your hands, legs, shoulders, or feet. You may want to work your way up and down your body tensing various muscle groups. Avoid tensing the muscles in any area of your body where you’re injured or in pain, as that may further aggravate your injury.\n\n3. Count\nFind a quiet and comfortable place to sit. Close your eyes and slowly count to 10. If necessary, repeat and count to 20 or an even higher number. Keep counting until you feel your anxiety subsiding. Sometimes this relief occurs quickly, but other times it might take a while. Stay calm and patient. Counting can relax you because it gives you something to focus on besides your anxiety. It’s a great tool to use in a crowded or busy space like a store or train where other anxiety exercises might be more challenging to carry out.", 
    link: "https://www.healthline.com/health/anxiety-exercises" },

    { title: "Having a rough day? Here are small ways to battle depression", 
    content: "1. Exercise.\nTake a 15- to 30-minute brisk walk every day. Or you can dance, play a sport, stretch, or do yoga. People who are depressed may not feel much like being active. Try to get yourself to do it anyway. If you need a push, ask a friend to exercise with you. Getting any activity started helps boost your mood. Keep it going.\n\n2. Regularly Eat Wholesome Foods\nWhen a person is depressed, they often tend to eat poorly. Sugary, salty, and high-fat junk food can bring a temporary feeling of comfort, but ultimately these foods cause spikes in blood sugar, weight gain, and bring on bad moods. The solution is finding wholesome foods you like, making sure you have plenty on hand, and eating these foods every day. Fresh fruit, salads, lean meats, oily fish such as salmon, and whole-grain bread are all good options, as long as you do not have a food allergy or another adverse reaction to the food. The critical point is finding wholesome foods you enjoy and training yourself to reach for these when hungry or feeling down.\n\n3. Make a Change in Routine\nMaking a change in routine does not need to be complicated. For example, instead of heading straight for the TV after getting home from work, commit to taking a short walk first. Instead of having an unhealthy dinner, make a small effort to eat a more healthy meal. Changing routines can help to rewire the pathways of dopamine in the brain, an important brain chemical linked to feelings of happiness. The changes in routine do not need to be large to have a positive effect.\n\n4. Notice good things.\nDepression affects a person's view of things. Things can seem dismal, negative, and hopeless. To shift your view, make it a goal to notice 3 good things every day. The more you notice what's good, the more good you will notice.\n\n5. Connect with a support system.\nCreating, sustaining and nurturing social relationships gives your mental health a boost. Make an effort to spend time with the people whose company you enjoy. It’s also important to identify someone or some people in your life to be open with about your feelings. Talk with them about what you’re going through, as this can help you feel better in the moment and strengthen your relationship.", 
    link: "https://kidshealth.org/en/teens/depression-tips.html" },

    { title: "Struggling with productivity? Here’s how to cope with ADHD",
    content: "When ADHD persists through early adulthood and on into middle age, it presents many of the same challenges it does in childhood: it’s hard to stay organized, start projects, stay on task, and meet deadlines. But now life is busier, and expectations from work and family often are even higher. Fortunately, there are lots of strategies that can help you navigate this time in your life.\n\n1. Stay organized by:\n* Setting aside time each day to update your schedules.\n* Using colors and lists in organization.\n* Keeping the phone off or in another room when you are trying to work.\n\n2. Stay focused by:\n* Decluttering your home and office.\n* Minimizing external commotion.\n* Jotting down ideas as they come to you.\n\n3. Stay on track by:\n* Putting off procrastinating.\n* Taking one thing at a time.\n* Dealing with emails, phone calls, or other matters as soon as you can.",
    link:"https://www.health.harvard.edu/blog/mid-life-adhd-coping-strategies-that-can-help-2021020521862"}
]